### ISSUE TITLE
Ubuntu cmake error

### ISSUE THREAD

**Issue by happydpc** [Pelagicore/facelift#222]
Command:
  /home/osboxes/Desktop/qml-workspace/facelift/codegen/facelift/facelift-codegen.py
  --input
  /home/osboxes/Desktop/qml-workspace/facelift/src/ipc/dbus/interfaces
  --output
  /home/osboxes/Desktop/qml-workspace/facelift/build/src/ipc/dbus/facelift_generated_tmp
  with
  PYTHONPATH=/home/osboxes/Desktop/qml-workspace/facelift/codegen/facelift/qface

  Return code: No such file or directory

  Output:

  Error:

Call Stack (most recent call first):
  src/ipc/dbus/CMakeLists.txt:12 (facelift_generate_code)

**Comment by jacky309** [comment]
You seem to be missing the QFace submodule initialization. The build instructions can be found at https://github.com/Pelagicore/facelift
